### ISSUE TITLE
Crossdeployment

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#4]
stub for now.

**Comment by alexsoble** [comment]
@hunterowens @almartin82 @chrishaid: Agreeing on a data standard will facilitate the technical side of crossdeployment. We should think about the product side too. 

How about a product-oriented phone call with:
- the three of us from Team Somerville
- the three of you from KIPP tech side / Impact Lab
- relevant people at KIPP from the instructional side
  - I'm thinking curriculum director type people here but maybe others — you all are more familiar with KIPP and who the product owners would be for this

Goal would be to gauge KIPP's interest in the Somerville student insights tool on the instructional side, and get a sense of what their key priorities would be for the product (since it's still in development).

**Comment by alexsoble** [comment]
@hunterowens @almartin82 @chrishaid: And we should do the same with Somerville leadership and the "Mint dot com for college readiness" app too!

**Comment by hunterowens** [comment]
+1.

**Comment by alexsoble** [comment]
@hunterowens @almartin82 @chrishaid: Do you have screenshots / a pitch / a deck / materials that help explain "Mint dot com for college readiness"? We are thinking about creating those kinds of materials for the Student Insights product.

**Comment by hunterowens** [comment]
We have some of the materials we used to get funding (deck for 1 foundation, 1 page writeup) but no mockups yet. @almartin82 would be able to release (don't think we can put out in public.)

**Comment by hunterowens** [comment]
@alexsoble I suspect @almartin82 and @chrishaid are going to be pretty busy this week getting ready for KIPP Data, so let's try and do this next week.

**Comment by hunterowens** [comment]
As of today, KIPP NJ has a running production copy of student insights. Thanks to everybody for their hard work!

**Comment by almartin82** [comment]
agreed! :+1:

(mobile)

**Comment by alexsoble** [comment]
Woohoo! :tada: :tada:
