### ISSUE TITLE
Extract Tooling

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#5]
Hi All-

After speaking with @almartin82 today, looks like we need to write at least two robots to extract data- Roster and other info from SIS, and [NWEA MAP](https://teach.mapnwea.org/cas/nweaLogin?service=https%3A%2F%2Fteach.mapnwea.org%2Fadmin%2F) scores. @alexsoble has written some [Aspen X2 extract scripts](https://teach.mapnwea.org/cas/nweaLogin?service=https%3A%2F%2Fteach.mapnwea.org%2Fadmin%2F) as well. Andrew has written a bunch of code around the MAP as well. 

Proposal: Under the guise of the openEduConnect organization, we write a single software package that extracts data from a system and transforms it into uniform format. This package is then used by the two implementation apps to load data. We use a variety of technologies/languages (Python, R, Ruby), so I'm not sure how exactly to architect this [1], but wanted to get the idea out there. 

Questions/Comments/Concerns/Existential Crises?  

[1] Rough idea: a Docker container, than given credentials to the proper system, dumps a CSV or SQLite DB. That way, any app could shell out and do `docker run -d crendentials_file.txt` but I'm not sure how exactly to built that.

**Comment by alexsoble** [comment]
**Question:**
- Since Somerville is already running the X2 export scripts nightly, would productizing the extraction add value for Somerville? Or is this just about making it easier for future school districts to adopt/extract? (Okay either way, want to make sure I understand.)

**Comment:**
- We should validate interest in product cross-deployment before we build an extractor tool. For the extraction to be valuable for KIPP/Somerville, school leadership needs to know what products or technical benefits the extraction will get them. This will also help sharpen the specs for the tooling.

**Comment by hunterowens** [comment]
To answer your question, no additional value for Somerville, but lots of value for crossdeployment, DRY, etc. 

To respond for your comment, KIPP, through having separate regions, has a vested interested in cross-deployment, therefore, the need for a robust bot. From a Technical side, KIPP NJ->KIPP NYC is the same as KIPP NJ->alternative district)

**Comment by alexsoble** [comment]
Oooh. Makes sense! Didn't understand the KIPP NJ => KIPP NYC part. Thanks @hunterowens!

**Comment by hunterowens** [comment]
No Worries, no reason you would have. Happy to explain.
