### ISSUE TITLE
Integration Hack Session Planning.

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#8]
I'm in SF 7/30-31. @alexsoble and I are planning on making a sprint to hopefully get KIPP<->Somerville playing nice with each others applications. This is a planning thread.

**Comment by alexsoble** [comment]
It's on my calendar! I will vigorously keep those days clear and we shall hack together toward #4.

**Comment by hunterowens** [comment]
Sweet. Also, thoughts on getting the greater CfA community involved?

**Comment by alexsoble** [comment]
Interesting! What are you thinking? If we can define a few specific chunks of work that are modular, would love to invite other fellows to come hack with us. Unfortunately no brigade meetings on those days, otherwise would be great to get brigade folks involved. 

What kinds of help will we want and how could we best involve people?

**Comment by hunterowens** [comment]
I think one way of talking about it is I can give my student data, for
students pitch OR the edu data landscape talk that @almartin and @jpvelez
have. Otherwise, figuring out some sorts of modules for people to hack on
could be cool.

**Comment by alexsoble** [comment]
Ah gotcha! Or both. Pitch plus hacking together.

**Comment by hunterowens** [comment]
This happened.
