### ISSUE TITLE
Align data schemas

### ISSUE THREAD

**Issue by alexsoble** [openEduConnect/edu-data-standards#9]
Here's the [current data schema](https://github.com/openEduConnect/edu-data-standards/files/500/erd.pdf) we're using on the [Somerville Student Insights tool](https://github.com/codeforamerica/somerville-teacher-tool):

![data model](https://cloud.githubusercontent.com/assets/3209501/8489495/bcf87b1a-20d0-11e5-8e56-96d71c3611a7.png)

TODOs include abstracting McasResult and StarResult into a more broad Assessment model.

Generally interested in aligning closer to Ed-Fi #1 until/unless we settle on a different standard, with the overall goal of getting both the CfA/Somerville project and the KIPP project toward #4.

Thoughts on the current schema? Ways it could be improved? @hunterowens @almartin82

**Comment by alexsoble** [comment]
P.S.  Thanks to @thfield for plugging [Rails ERD](https://github.com/voormedia/rails-erd) into our app so we can make pretty diagrams like this.

**Comment by hunterowens** [comment]
I'm thinking long and hard about this. Will respond with more soon.

**Comment by alexsoble** [comment]
:+1: :+1:

**Comment by hunterowens** [comment]
Ok. More Thoughts: 

Every application is going to have an internal schema the one that is above. Developers of an application want this to be easy to change, because that makes their application easy to built. Furthermore, certain fields/features (ie, IP address) wouldn't be part of a larger schema. 

The [CEDS](https://ceds.ed.gov/) and EdFi standards give us an idea of how to name fields. What we should do is write mapping from SIS/Assignment Provider->CEDS/EdFi (just as CSVs probably)->Application Schemas. Thoughts? We may want to rationalize names in the application schema to make migration easier.

**Comment by hunterowens** [comment]
I should also mention that CEDS provides a series of `CREATE TABLE ...` statements for MS SQL Server. We could port that to PostgreSQL.

**Comment by almartin82** [comment]
@hunterowens agreed that you don't want to constrain the internal schema -- so much overhead.  you do want to make it easy to move from internal to external.  so agreed on the mapping, but we should also look at what CEDS does first before rolling our own structure from scratch.

**Comment by alexsoble** [comment]
@almartin82 This makes sense! Coworking with @hunterowens today, we hashed this out. CEDS looks like the right place to start, naming-wise. And agreed we want to separate internal schemas from the interoperability / data standards discussion.
